### ISSUE TITLE
## Build fails on ESPHome 2026.8.1+: `IPAddress::str()` has no member named `str`

### ISSUE THREAD

**Issue by vlanwalker** [boneIO-eu/esphome#49]
Compiling with ESPHome **2026.8.1** fails because `packages/devices_v0_7/display.yaml` calls the deprecated `IPAddress::str()` method, which was removed in ESPHome **2026.8.0** (it was deprecated back in 2026.2.0 with a removal notice — see [esphome `ip_address.h`](https://api-docs.esphome.io/ip__address_8h_source), line 150: `// Remove before 2026.8.0`).

### Environment

- ESPHome version: 2026.8.1
- Package: `boneIO-eu/esphome@packages-v2.0.0`
- Device config: `boneio-c-07-f3dfa0.yaml`
- Tested on device: [[boneIO ESP Cover](https://store.boneio.eu/pl/produkt/boneio-esp-cover/)](https://store.boneio.eu/pl/produkt/boneio-esp-cover/)
- Affected file: `packages/devices_v0_7/display.yaml`, line 36

### Steps to reproduce

1. Use the `packages-v2.0.0` boneIO package with a `display.yaml` device include on ESP32 with ethernet.
2. Compile with ESPHome 2026.8.1 or newer.
3. Build fails during `Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/main.cpp.obj`.

### Error output

```
/data/packages/b521bca1/packages/devices_v0_7/display.yaml: In lambda function:
/data/packages/b521bca1/packages/devices_v0_7/display.yaml:36:85: error: 'std::array<esphome::network::IPAddress, 5>::value_type' {aka 'struct esphome::network::IPAddress'} has no member named 'str'
   36 |       return id(eth).get_ip_addresses().empty() ? "Unset" : id(eth).get_ip_addresses()[0].str();
      |                                                                                     ^~~
```

### Root cause

`IPAddress::str()` was removed from ESPHome core in 2026.8.0. The replacement API is `str_to(char *buf)`, which writes into a caller-provided buffer instead of returning a `std::string`.

### Suggested fix

In `packages/devices_v0_7/display.yaml`, line 36, replace:

```cpp
return id(eth).get_ip_addresses().empty() ? "Unset" : id(eth).get_ip_addresses()[0].str();
```

with:

```cpp
if (id(eth).get_ip_addresses().empty()) return std::string("Unset");
char buf[46];
return std::string(id(eth).get_ip_addresses()[0].str_to(buf));
```

This keeps the same return type (`std::string`) and behavior, while using the current, non-deprecated API. It also avoids the compile break for anyone on ESPHome ≥2026.8.0.

### Additional notes

The same file also triggers a deprecation warning (not yet a hard error) for `Sensor::raw_state`, which ESPHome says will be removed in **2026.10.0**:

```
/data/packages/b521bca1/packages/devices_v0_7/display.yaml:12:48: warning: 'esphome::sensor::Sensor::raw_state' is deprecated: Use get_raw_state() instead of .raw_state. Will be removed in 2026.10.0
```

It would be worth fixing this in the same pass to avoid a second breaking build once 2026.10.0 lands — replace `id(wt32_uptime_seconds).raw_state` with `id(wt32_uptime_seconds).get_raw_state()`.

Happy to open a PR with these two changes if that's easier than a maintainer picking it up.

**Comment by vlanwalker** [comment]
Just found out that this is already fixed on main — it landed in [PR #47](https://github.com/boneIO-eu/esphome/pull/47) ("Fix build warnings", commits 48a0c5d/d962a57/adfb6a3) before the bump to ESPHome 2026.8.1 in 66cb515.

Both packages/devices_v0_7/display.yaml lines are already updated on main / tag packages-v2.1.0:


if (id(eth).get_ip_addresses().empty()) return {"Unset"};
char buf[esphome::network::IP_ADDRESS_BUFFER_SIZE];
id(eth).get_ip_addresses()[0].str_to(buf);
return {buf};
and


int seconds = round(id(wt32_uptime_seconds).get_raw_state());
I confirmed the old .str() / .raw_state code only exists at the packages-v2.0.0 tag you're pinned to — it's gone by packages-v2.1.0.

Fix: bump the package ref: in your device config from packages-v2.0.0 to packages-v2.1.0 (or later) and it should compile cleanly against ESPHome 2026.8.1+. No code change needed here — closing as already resolved, but shout if v2.1.0 still doesn't build for you.
